apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: config-efk
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: manifests/efk/install
    repoURL: https://github.com/christianh814/openshift-cluster-config-expand
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 15 # number of failed sync attempt retries; unlimited number of attempts if less than 0
      backoff:
        duration: 15s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 30m # the maximum amount of time allowed for the backoff strategy
